version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      ##MONGO_INITDB_ROOT_USERNAME: root
      ##MONGO_INITDB_ROOT_PASSWORD: fw324fe
      MONGODB_DATABASE: nest-pokemon
    volumes:
      - './mongo-volume:/data/db'
